language: python

python:
  - "2.6"
  - "2.7"
  - "3.6"

install:
  - pip install . --quiet --use-mirrors
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install importlib --quiet; fi"
  - pip install nose simplejson Flask-SQLAlchemy Flask-MongoEngine Flask-Peewee Flask-Mail mock MySQL-python --quiet
  - pip install oauth2client google-api-python-client foursquare python-twitter --quiet
  - pip install http://github.com/pythonforfacebook/facebook-sdk/tarball/master --quiet

before_script:
  - mysql -e 'create database flask_social_test;'

services:
  - mongodb

script: nosetests

branches:
  only:
    - master
    - develop
